image:
  file: Dockerfile
tasks:
- command: >
    mkdir --parents build &&
    cd build &&
    cmake .. &&
    make &&
    ./tinyraycaster &&
    pnmtopng out.ppm > out.png &&
    open out.png &&
    cd ..
